- 👋 Hi, I’m @Senbonzakura1234
- 👀 I’m interested in Typescript
- 🌱 Working with Nextjs for 3 years
- 💞️ I’m looking to collaborate on any React Typescript Projects
- 📫 How to reach me: [Linkedin](https://www.linkedin.com/in/anh-dung-pham-9ab7761b2/)
