import PageTitle from '@root/components/PageTitle';
import { type NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Sophie Dex</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex h-screen flex-col items-center justify-center'>
				<PageTitle pageName='Atelier Dex' />
			</main>
		</>
	);
};

export default Home;
